name: Upload Media to Cloudinary
on:
  push:
    paths:
      - 'content/images/**'
      - 'content/posts/**'

jobs:
  upload-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # 或 1.1.30

      - name: Install dependencies
        run: bun ci  # 替换 npm ci，速度提升 5-10x

      - name: Upload images to Cloudinary
        uses: emmanuelgautier/cloudinary-upload-action@v2
        with:
          cloud_name: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          api_key: ${{ secrets.CLOUDINARY_API_KEY }}
          api_secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          # folder: 'your-folder-name'  # 可选：指定上传到 Cloudinary 的文件夹
          src: 'content/images/**'  # 指定要上传的文件路径
        # env:
        #   CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        #   CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        #   CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # run: bunx scripts/upload-to-cloudinary.ts
